#
# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

#AES-128(16bit)
encryption:
  key: "1234567890ABCDEF"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    defaultModelsExpandDepth: 1


Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
