#
# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_card
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

#AES-128(16bit)
encryption:
  key: "1234567890ABCDEF"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN   
    org.springframework.boot: INFO
    org.springframework: INFO
    org.springdoc: INFO
    liquibase: INFO
    
jwt:
  secret: "superSecretKeyForJwt1234567890superSecretKey"
  expiration: 3600000 


Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
